server {
    listen 80;
    server_name _;
    resolver 127.0.0.11 valid=30s ipv6=off;
    client_max_body_size 50m;

    root /usr/share/nginx/html;
    index index.html;

    location /api/ {
        set $fastsell_api http://fastsell-api:8888;
        proxy_pass $fastsell_api;
        proxy_http_version 1.1;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    location = /health {
        set $fastsell_api_health http://fastsell-api:8888/health;
        proxy_pass $fastsell_api_health;
        proxy_http_version 1.1;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    location = /health/db {
        set $fastsell_api_health_db http://fastsell-api:8888/health/db;
        proxy_pass $fastsell_api_health_db;
        proxy_http_version 1.1;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    location /assets/ {
        try_files $uri =404;
        access_log off;
        expires 1h;
        add_header Cache-Control "public";
    }

    location / {
        try_files $uri $uri/ /index.html;
    }
}
